### ISSUE TITLE
error in script

### ISSUE THREAD

**Issue by Q1984** [hausec/ProxyLogon#1]
Hello,

I've tested it, but gives me the following error.

File "proxylogon.py", line 162, in <module>
    oabId = ct.content.split('"RawIdentity":"')[1].split('"')[0]
IndexError: list index out of range

**Comment by Lulztigre** [comment]
use python3?

**Comment by Q1984** [comment]
With python3

[+] Attempting SSRF
Traceback (most recent call last):
  File "proxylogon.py", line 68, in <module>
    if "<LegacyDN>" not in ct.content:
TypeError: a bytes-like object is required, not 'str'

**Comment by hausec** [comment]
This project is not supported.
