### ISSUE TITLE
LegacyDN issue

### ISSUE THREAD

**Issue by Kinny092** [hausec/ProxyLogon#3]
Hi,

I set up Server 2016 and Exchange 2016 with default configuration in a VM. 

Hostname is currently DC1.BMOSystems.net
IP address is currently 192.168.1.100

I tried to run the command in my Parrot OS box and I get the below error.
I have also added my DC1 to host file, and I can PING DC1.
![image](https://user-images.githubusercontent.com/25901267/116784259-cb681b00-aa82-11eb-8083-5e733b0472b7.png)
Thanks

**Comment by Kinny092** [comment]
When I run the select objects command for Administrator through powershell, below is my LegacyExchangeDN
![image](https://user-images.githubusercontent.com/25901267/116784309-c337cc00-aad2-11eb-8f20-3b7a9d8000ab.png)

**Comment by hausec** [comment]
This project is unsupported. https://github.com/hausec/ProxyLogon#support

**Comment by telechubaiz** [comment]
> When I run the select objects command for Administrator through powershell, below is my LegacyExchangeDN
> ![image](https://user-images.githubusercontent.com/25901267/116784309-c337cc00-aad2-11eb-8f20-3b7a9d8000ab.png)

basically read the code and fix the goddamn error.

**Comment by hausec** [comment]
> 
> 
> > When I run the select objects command for Administrator through powershell, below is my LegacyExchangeDN
> > ![image](https://user-images.githubusercontent.com/25901267/116784309-c337cc00-aad2-11eb-8f20-3b7a9d8000ab.png)
> 
> basically read the code and fix the goddamn error.

https://github.com/hausec/ProxyLogon#support

basically read the readme and fix your own goddamn error.
