### ISSUE TITLE
File "proxylogon.py", line 162, in <module>

### ISSUE THREAD

**Issue by 13Ragna37** [hausec/ProxyLogon#4]
Hey, what do i wrong?

Target: ex01.test.local
=============================
[+] Attempting SSRF
DN: /o=test/ou=Exchange Administrative Group (FYDIBOHF234DFG)/cn=Recipients/cn=user2k84c371
Original SID: S-1-5-21-2618403723-285310027-452162228-3400
Corrected SID: S-1-5-21-2618403723-285310027-452162228-500
[+] SSRF Successful!
[+] Attempting Arbitrary File Write
SessionID: 7197cb40-1055-4f66-a819-207b77f14cd4
CanaryToken: pHGGBD4i0keGb02Q9fMFxxbunZ2xWdkIz893WmBEoYDclsv1JsfZ00NG1AzxLy7qn7vr4Y50bW4.
Traceback (most recent call last):
  File "proxylogon.py", line 162, in <module>
    oabId = ct.content.split('"RawIdentity":"')[1].split('"')[0]
IndexError: list index out of range

**Comment by hausec** [comment]
Project not supported, RTFM
